build-gen-idx:
  generated-by: uVision version 5.41.0.0
  generators:
    - board: ""
      device: STM32F429ZITx
      id: CubeMX
      output: C:/Users/jandr/GitHub/Uni 2024/Embedded-Systems/Tasks/A Project/STM32CubeMX/Target_1/
      project-type: single-core
      cbuild-gens:
        - cbuild-gen: C:/Users/jandr/GitHub/Uni 2024/Embedded-Systems/Tasks/A Project/project test.Target_1.cbuild-gen.yml
          configuration: .Target_1
          name: C:/Users/jandr/GitHub/Uni 2024/Embedded-Systems/Tasks/A Project/STM32CubeMX/Target_1/project test.cgen.yml
          project: project test